<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TheWatch.Geospatial.Db</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TheWatch.Contracts\TheWatch.Contracts.csproj" />
  </ItemGroup>
</Project>
